keywords = {
    "Article 4": [
        # Core terms
        "personal data", "data subject", "identifiable", "identified",
        "processing", "automated means", "collection", "recording",
        "organisation", "structuring", "storage", "adaptation", "alteration",
        "retrieval", "consultation", "use", "disclosure", "transmission",
        "dissemination", "alignment", "combination", "restriction",
        "erasure", "destruction",

        # Profiling
        "profiling", "evaluate personal aspects", "automated processing",
        "predict behaviour", "economic situation", "location", "movements",

        # Pseudonymisation
        "pseudonymisation", "additional information", "separately stored",
        "technical measures", "organisational measures",

        # Filing system
        "filing system", "structured data", "criteria", "centralised",
        "decentralised", "geographical basis",

        # Roles
        "controller", "determines purpose", "determines means",
        "processor", "on behalf of controller",
        "recipient", "disclosure", "third party",
        "representative", "designated", "Union establishment",

        # Consent
        "consent", "freely given", "informed", "unambiguous", "affirmative action",

        # Breach
        "personal data breach", "security breach", "unlawful disclosure",
        "unauthorised access", "loss", "alteration",

        # Special data
        "genetic data", "inherited", "acquired", "biological sample",
        "biometric data", "facial images", "dactyloscopic data",
        "health data", "health status", "healthcare services",

        # Enterprise
        "enterprise", "economic activity", "group of undertakings",
        "controlling", "controlled", "binding corporate rules",

        # Supervisory
        "supervisory authority", "Article 51", "cross-border processing",
        "relevant and reasoned objection", "information society service",
        "international organisation", "public international law",

        # Recital-related terms
        "technology neutrality", "anonymous data", "online identifiers",
        "profiling", "public authorities", "main establishment"],
    
    "Article 5": ["lawfulness", "fairness", "transparency", "purpose limitation", "specified purposes", "explicit purposes", "legitimate purposes", "data minimisation", "adequate", "relevant", "limited", "accuracy", "up to date", "rectify", "erase", "storage limitation", "identification", "retention period", "integrity", "confidentiality", "security", "unauthorised processing", "unlawful processing", "accidental loss", "destruction", "damage", "technical measures", "organisational measures", "accountability", "controller responsibility", "demonstrate compliance", "lawful", "store", "protect"],
    "Article 6": ["legal basis", "data subject consent", "contract performance",
                    "legal obligation", "vital interests", "public task", 
                    "legitimate interests", "necessary for processing", "explicit consent",
                    "withdrawal of consent", "balancing test", "contract", "encryption", 
                    "restricted access", "security audit", "data protection protocols"],
    "Article 7": ["consent", "demonstrate consent", "written declaration", "clear and plain language", "withdraw consent", "informed consent", "easy to withdraw", "freely given", "contract condition", "conditional consent", "separate consent", "non-binding clause"],
    "Article 8": ["child's consent", "information society services", "age of consent", "parental responsibility", "verify consent", "age limit", "age verification", "contract law", "child protection"],
    "Article 9": ["special categories", "sensitive data", "racial origin", "ethnic origin", "political opinions", "religious beliefs", "philosophical beliefs", "trade union", "genetic data", "biometric data", "health data", "sex life", "sexual orientation", "explicit consent", "employment law", "social security", "vital interests", "not-for-profit", "manifestly public", "legal claims", "public interest", "preventive medicine", "occupational medicine", "healthcare", "public health", "research purposes", "archiving", "professional secrecy", "Article 89(1)"],
    "Article 10": ["criminal data", "criminal convictions", "offences", "security measures", "official authority", "authorised by law", "appropriate safeguards", "criminal records", "comprehensive register", "Member State law", "Union law"],
    "Article 11": ["non-identification", "not required to identify", "no additional data", "anonymous processing", "unidentifiable data subject", "controller not obliged", "inability to identify", "Articles 15 to 20", "additional information", "data subject rights"],
    "Article 12": ["transparent information", "clear and plain language", "concise", "intelligible", "accessible format", "electronic means", "oral request", "data subject rights", "facilitate rights", "response time", "within one month", "extension", "reason for delay", "refusal to act", "complaint right", "judicial remedy", "free of charge", "unfounded request", "excessive request", "reasonable fee", "verify identity", "standardised icons", "machine-readable icons", "visual indicators", "delegated acts"],
    "Article 13": ["information at collection", "controller identity", "DPO contact", "processing purpose", "legal basis", "legitimate interests", "data recipients", "data transfer", "third country", "adequacy decision", "appropriate safeguards", "storage period", "retention", "data access", "rectification", "erasure", "restriction", "objection", "data portability", "withdraw consent", "supervisory authority", "complaint right", "contractual requirement", "statutory requirement", "automated decision-making", "profiling", "Article 22", "further processing", "existing information"],
    "Article 14": ["indirect data collection", "controller identity", "DPO contact", "processing purpose", "legal basis", "data categories", "recipients", "third country", "adequacy decision", "appropriate safeguards", "storage period", "retention", "legitimate interests", "data access", "rectification", "erasure", "restriction", "objection", "data portability", "withdraw consent", "complaint right", "data source", "publicly accessible source", "automated decision-making", "profiling", "Article 22", "timing of notice", "first communication", "disproportionate effort", "confidentiality", "professional secrecy"],
    "Article 15": ["right of access", "confirmation of processing", "personal data access", "processing purpose", "data categories", "recipients", "third country transfers", "storage period", "retention", "rectification", "erasure", "restriction", "objection", "complaint right", "data source", "automated decision-making", "profiling", "Article 22", "logic involved", "consequences", "copy of data", "reasonable fee", "electronic form", "rights of others", "access to your personal information", "request a copy of your data", "obtain your data", "information about your data", "what data we hold", "how we process your data", "subject access request"],
    "Article 16": ["rectification", "correct inaccurate data", "complete incomplete data", "supplementary statement", "right to correct data", "update personal data"],
    "Article 17": ["erasure", "right to be forgotten", "withdraw consent", "unlawful processing", "legal obligation to erase", "data no longer necessary", "object to processing", "public information society services", "inform other controllers", "freedom of expression exception", "legal compliance exception", "public interest exception", "research exception", "legal claims exception", "erase public data", "reasonable steps", "delete your data", "remove your information", "right to deletion", "request deletion", "right to remove", "deletion protocols"],
    "Article 18": ["restriction of processing", "contest accuracy", "unlawful but no erasure", "retain for legal claims", "objected to processing", "pending verification", "consent required for processing", "protect rights of others", "important public interest", "inform before lifting restriction"],
    "Article 19": ["notification to recipients", "inform about rectification", "inform about erasure", "inform about restriction", "communication duty", "disclosure updates", "data subject request"],
    "Article 20": ["data portability", "receive personal data", "structured format", "machine-readable format", "transmit to another controller", "automated processing", "based on consent", "contractual processing", "no hindrance", "direct transmission", "technical feasibility", "rights and freedoms of others"],
    "Article 21": ["object to processing", "grounds of personal situation", "Article 6(1)(e)", "Article 6(1)(f)", "object to profiling", "object to direct marketing", "automated means", "research objection", "public interest exception", "information society services"],
    "Article 22": ["automated decision-making", "profiling", "legal effects", "significant effects", "human intervention", "express viewpoint", "contest decision", "contract necessity", "explicit consent", "authorised by law", "special categories", "safeguards"],
    "Article 23": ["restriction of rights", "national security", "public security", "criminal investigation", "judicial independence", "professional secrecy", "civil law claims", "important public interest", "financial interest", "inspection functions", "safeguards", "legislative measures", "confidentiality", "disclosure limitation"],
    "Article 24": ["accountability", "controller responsibility", "technical and organisational measures", "risk-based approach", "demonstrate compliance", "update measures", "data protection policies", "certification mechanisms", "codes of conduct"],
    "Article 25": ["data protection by design", "data protection by default", "pseudonymisation", "minimisation", "limit data collection", "access control", "default privacy", "storage limitation", "privacy safeguards", "technical and organisational measures", "certification mechanism", "privacy by design principles", "privacy by default principles", "built-in privacy", "privacy from the outset", "privacy-enhancing technologies", "embed data protection", "system design"],
    "Article 26": ["joint controllers", "shared responsibilities", "transparent arrangement", "data subject contact point", "controller agreement", "shared accountability", "exercise of rights", "Articles 13 and 14", "essence of arrangement", "multiple controllers"],
    "Article 27": ["non-EU controller", "non-EU processor", "EU representative", "Article 3(2)", "written mandate", "supervisory authority liaison", "data subject contact", "established in member state", "exemptions for public bodies", "occasional processing", "no large-scale sensitive data", "limited risk processing"],
    "Article 28": ["processor obligations", "processing on behalf of controller", "processor contract", "documented instructions", "sub-processor approval", "technical measures", "organisational measures", "confidentiality", "data security", "data subject rights support", "audit support", "deletion or return of data", "contractual clauses", "certification mechanism", "joint liability", "unauthorised instruction", "standard contractual clauses", "Article 32 compliance", "Article 9(1) data", "Article 10 data"],
    "Article 29": ["processing under authority", "controller instructions", "processor instructions", "lawful processing", "personal data access", "data confidentiality", "internal processing controls"],
    "Article 30": ["processing records", "record of processing activities", "data categories", "data subject categories", "recipient categories", "third country transfers", "safeguards", "controller details", "DPO", "security measures", "retention limits", "processor records", "electronic form", "250 employees exemption", "supervisory authority access", "data processing records", "maintain records", "documentation of processing", "register of processing activities"],
    "Article 31": ["supervisory authority", "data protection authority", "cooperate with authority", "controller cooperation", "processor cooperation"],
    "Article 32": ["security measures", "technical measures", "organisational measures", "pseudonymisation", "encryption", "confidentiality", "integrity", "availability", "resilience", "data breach prevention", "restore access", "risk-based security", "testing and evaluation", "data security", "data encryption", "secure processing", "security of processing", "access controls", "data protection measures", "technical and organizational measures", "ISO/IEC 27001 controls"],
    "Article 33": ["data breach", "breach notification", "72 hours", "controller obligation", "processor obligation", "supervisory authority", "contact details", "mitigation measures", "breach consequences", "documentation of breach"],
    "Article 34": ["data breach notification", "inform data subjects", "high risk", "clear language", "encryption", "risk mitigation", "public communication", "supervisory authority decision"],
    "Article 35": ["DPIA", "impact assessment", "high risk processing", "automated decision-making", "large-scale processing", "sensitive data", "systematic monitoring", "mitigation measures", "risk evaluation", "consult supervisory authority", "AI-driven service"],
    "Article 36": ["prior consultation", "supervisory authority", "high risk processing", "lack of mitigation", "consultation process", "controller duties", "Article 35", "public interest task", "Member State law", "processing advice", "legislative measure"],
    "Article 37": ["DPO", "data protection officer", "designation", "public authority", "large scale monitoring", "sensitive data", "expert knowledge", "contact details", "single DPO", "service contract", "appointed DPO", "DPO contact", "contact our DPO", "data protection contact"],
    "Article 38": ["DPO independence", "DPO support", "no instruction", "no dismissal", "management access", "data subject contact", "confidentiality", "conflict of interest"],
    "Article 39": ["DPO tasks", "inform and advise", "monitor compliance", "DPIA advice", "cooperation with authority", "contact point", "training and audits", "data protection obligations"],
    "Article 40": ["codes of conduct", "industry standards", "sector-specific rules", "controller associations", "data subject rights", "data transfer safeguards", "supervisory authority approval", "Board opinion", "binding commitments", "out-of-court dispute resolution", "Article 46 compliance"],
    "Article 41": ["code of conduct", "monitoring", "accreditation", "independent body", "expertise", "eligibility procedures", "compliance review", "complaint mechanisms", "conflict of interest", "supervisory authority", "consistency mechanism", "suspension", "exclusion", "revocation of accreditation", "not applicable to public bodies"],
    "Article 42": ["certification", "data protection seals", "GDPR compliance", "voluntary", "SMEs", "non-EU controllers/processors", "appropriate safeguards", "transparent process", "European Data Protection Seal", "supervisory authority", "Board approval", "certification validity", "certification withdrawal", "register of certifications"],
    "Article 43": ["certification bodies", "accreditation", "supervisory authority", "national accreditation body", "independence", "technical expertise", "conflict of interest", "certification procedures", "complaint handling", "five-year validity", "withdrawal", "delegated acts", "implementing acts", "publication of criteria", "revocation of accreditation"],
    "Article 44": ["data transfers", "third countries", "international organisations", "onward transfers", "GDPR conditions", "protection of personal data", "level of protection", "non-undermining", "Chapter V compliance", "international transfers", "cross-border transfers", "SCCs", "Standard Contractual Clauses", "Binding Corporate Rules", "BCRs", "adequacy status"],
    "Article 45": ["adequacy decision", "third country", "international organisation", "adequate level of protection", "European Commission", "rule of law", "human rights", "legislation", "supervisory authorities", "international commitments", "review mechanism", "suspension", "repeal", "monitoring", "implementing acts", "public list of decisions"],
    "Article 46": ["appropriate safeguards", "standard contractual clauses", "binding corporate rules", "certification mechanisms", "code of conduct", "enforceable rights", "legal remedies", "contractual clauses", "administrative arrangements", "supervisory authority", "consistency mechanism", "legacy authorisations", "Commission decisions"],
    "Article 47": ["binding corporate rules", "multinational data transfer", "legal binding", "enforceable rights", "group undertakings", "data protection principles", "onward transfers", "data subject rights", "complaints", "supervisory authority", "compliance monitoring", "liability", "internal procedures", "training", "cooperation mechanism"],
    "Article 48": ["third country requests", "court orders", "administrative decisions", "international agreement", "legal basis", "data disclosure restrictions", "Union law", "mutual legal assistance"],
    "Article 49": ["explicit consent", "contract necessity", "public interest", "legal claims", "vital interests", "public registers", "non-repetitive transfers", "limited data subjects", "legitimate interests", "supervisory authority notification", "data subject information", "legal documentation"],
    "Article 50": ["international cooperation", "data protection enforcement", "mutual assistance", "notification", "complaint referral", "investigative support", "stakeholder engagement", "legislative exchange", "jurisdictional conflicts", "Commission role", "supervisory authority cooperation"],
    "Article 51": ["supervisory authority", "independent authority", "fundamental rights", "data protection monitoring", "free flow of data", "national authorities", "EU consistency", "Board representation", "notification to Commission", "compliance mechanism"],
    "Article 52": ["independence", "external influence", "no instructions", "exclusive staff direction", "financial autonomy", "resources", "infrastructure", "public budget", "conflict of interest", "exclusive direction"],
    "Article 53": ["appointment procedure", "transparent selection", "qualifications", "experience", "skills", "term expiration", "resignation", "retirement", "dismissal", "serious misconduct"],
    "Article 54": ["legal establishment", "appointment procedures", "qualifications", "term length", "reappointment", "conflicts of interest", "employment cessation", "professional secrecy", "whistleblower protection"],
    "Article 55": ["supervisory authority competence", "territorial authority", "public authority processing", "Article 6(1)(c)(e)", "judicial independence", "non-applicability of Article 56"],
    "Article 56": ["lead supervisory authority", "main establishment", "cross-border processing", "Article 60 procedure", "local complaints", "substantial impact", "notification to lead authority", "case handling", "decision drafting", "exclusive interlocutor"],
    "Article 57": ["monitoring", "enforcement", "public awareness", "children's data", "government advisory role", "data subject information", "complaints handling", "investigations", "code of conduct", "certification", "data transfer", "Article 36 advice", "Article 35 list", "Article 47 BCR", "Board participation", "internal records", "standard clauses", "cooperation", "transparency", "free of charge service", "manifestly unfounded requests"],
    "Article 58": ["investigative powers", "corrective powers", "authorisation powers", "audits", "access to premises", "warnings", "reprimands", "order compliance", "suspension", "data breach communication", "certification withdrawal", "administrative fines", "Article 36 consultation", "codes of conduct", "binding corporate rules", "legal proceedings", "due process", "judicial remedy"],
    "Article 59": ["annual report", "types of infringement", "measures taken", "public transparency", "report to parliament", "report to government", "report to Board and Commission"],
    "Article 60": ["cooperation", "consensus", "mutual assistance", "joint operations", "draft decision", "reasoned objection", "revised draft", "consistency mechanism", "complaint rejection", "notification to controller", "controller compliance", "urgency procedure", "electronic exchange"],
    "Article 61": ["mutual assistance", "inter-authority cooperation", "information exchange", "prior authorisations", "inspections", "investigations", "response deadline", "one-month response", "standardised format", "refusal criteria", "electronic transmission", "no fee", "provisional measure", "Article 66 urgency"],
    "Article 62": ["joint investigations", "joint enforcement", "cross-border cases", "multi-state participation", "host and seconding authority", "investigative powers", "supervisory staff liability", "damage liability", "non-reimbursement", "urgent action", "Article 66 escalation", "Article 55 provisional measure"],
    "Article 63": ["consistent application", "cooperation", "Commission involvement", "Board facilitation", "cross-border uniformity", "coherent enforcement", "Section 2 procedures"],
    "Article 64": ["Board opinion", "draft decisions", "Article 35 DPIA list", "codes of conduct", "certification bodies", "standard clauses", "contractual clauses", "binding corporate rules", "Article 61 and 62 non-compliance", "electronic communication", "standardised format", "Board review period", "final decision notification"],
    "Article 65": ["binding decision", "dispute resolution", "reasoned objection", "lead authority conflict", "Article 60(4)", "Board majority vote", "final decision timeline", "publication", "controller notification", "Commission notification", "Article 64 conflict", "adoption without delay", "Article 66 urgency"],
    "Article 66": ["urgency", "exceptional circumstances", "provisional measures", "rights protection", "derogation from consistency mechanism", "immediate action", "territorial measures", "legal effect", "Board communication", "urgent opinion", "urgent binding decision", "two-week deadline"],
    "Article 67": ["information exchange", "electronic communication", "standardised format", "implementing acts", "supervisory authority coordination", "Commission powers", "Article 64 procedures"],
    "Article 68": ["EDPB", "legal personality", "Board composition", "Chair", "representatives", "joint representation", "Commission participation", "non-voting", "European Data Protection Supervisor", "voting rights"],
    "Article 69": ["Board independence", "no external instructions", "autonomous decisions", "Commission requests", "unbiased authority"],
    "Article 70": ["guidelines", "recommendations", "best practices", "supervisory authority coordination", "DPIA", "data breach notification", "certification", "BCR", "international transfers", "Article 64 opinions", "Article 65 decisions", "consistency mechanism", "training", "cooperation", "icons", "adequacy decisions", "data transfer requirements", "public register"],
    "Article 71": ["annual report", "data protection review", "third countries", "international organisations", "binding decisions review", "Article 65 decisions", "guidelines assessment"],
    "Article 72": ["decision-making", "simple majority", "rules of procedure", "two-thirds majority", "internal governance"],
    "Article 73": ["Board Chair", "deputy chairs", "election", "term of office", "renewable term"],
    "Article 74": ["Chair duties", "meeting preparation", "decision notification", "consistency mechanism coordination", "task management"],
    "Article 75": ["Board secretariat", "EDPS support", "administrative support", "translation", "communication", "operational logistics", "memorandum of understanding", "reporting lines"],
    "Article 76": ["Board discussions", "confidentiality", "rules of procedure", "access to documents", "third-party access", "Regulation (EC) No 1049/2001", "document transparency"],
    "Article 77": ["data subject rights", "lodge complaint", "supervisory authority", "place of residence", "alleged infringement", "right to remedy", "Article 78 reference"],
    "Article 78": ["judicial remedy", "supervisory authority decisions", "failure to act", "binding decisions", "Member State courts", "Article 77 reference", "consistency mechanism"],
    "Article 79": ["controller liability", "processor liability", "judicial remedy", "rights infringement", "habitual residence", "controller establishment", "public authority exception"],
    "Article 80": ["third-party representation", "not-for-profit organisation", "mandated representation", "Article 77", "Article 78", "Article 79", "Article 82", "independent complaints"],
    "Article 81": ["parallel proceedings", "court coordination", "same controller", "same subject matter", "jurisdiction", "suspension of cases", "consolidation of actions"],
    "Article 82": ["data subject compensation", "material damage", "non-material damage", "controller liability", "processor liability", "joint liability", "exemption from liability", "full compensation", "contribution claims", "Article 79(2)"],
    "Article 83": ["administrative fines", "proportionality", "dissuasion", "severity factors", "turnover-based fines", "intent or negligence", "previous infringements", "mitigation", "data category", "notification behavior", "Article 58 powers", "Member State discretion", "national courts", "certification", "supervisory authority powers", "GDPR fines", "non-compliance penalties", "sanctions", "regulatory action", "legal consequences"],
    "Article 84": ["Member State penalties", "non-administrative sanctions", "implementation obligation", "notification to Commission", "proportionate penalties", "effective penalties"],
    "Article 85": ["freedom of expression", "journalistic purposes", "academic purposes", "artistic purposes", "literary purposes", "national law", "exemptions", "derogations", "GDPR reconciliation", "Chapter exemptions"],
    "Article 86": ["official documents", "public authority", "task in public interest", "data disclosure", "access rights", "Member State law", "Union law", "data protection reconciliation"],
    "Article 87": ["national ID", "identifiers", "Member State law", "processing conditions", "safeguards", "data subject rights", "general application identifiers"],
    "Article 88": ["employment data", "employee rights", "recruitment", "workplace data", "performance monitoring", "termination", "collective agreements", "data transfers in groups", "transparency", "workplace monitoring"],
    "Article 89": ["archiving", "scientific research", "historical research", "statistical purposes", "pseudonymisation", "derogations", "data minimisation", "Article 15", "Article 16", "Article 18", "Article 19", "Article 20", "Article 21"],
    "Article 90": ["professional secrecy", "legal secrecy", "supervisory powers", "Member State rules", "confidential data", "controller obligations"],
    "Article 91": ["churches", "religious associations", "existing rules", "compliance with GDPR", "supervisory authority"],
    "Article 92": ["delegated acts", "Commission powers", "revocation", "notification", "entry into force", "European Parliament", "Council oversight"],
    "Article 93": ["committee", "Regulation 182/2011", "Commission assistance", "Article 5", "Article 8"],
    "Article 94": ["Directive 95/46/EC", "repeal", "transitional provisions", "Working Party", "EDPB", "reference interpretation"],
    "Article 95": ["ePrivacy Directive", "Directive 2002/58/EC", "public communication networks", "electronic communications", "no additional GDPR obligations"],
    "Article 96": ["international agreements", "third countries", "data transfer", "pre-2016 agreements", "validity", "Union law compliance"],
    "Article 97": ["review", "reporting", "Article 45", "Article 25(6)", "Chapter V", "Chapter VII", "amendment proposals", "technological developments"],
    "Article 98": ["harmonization", "amendments", "Union law consistency", "data processing by EU bodies", "legislative proposals"],
    "Article 99": ["entry into force", "25 May 2018", "Official Journal", "application date"]
}