titles = {
    "Artikel 4": "Definities en sleutelbegrippen",
    "Artikel 5": "Beginselen inzake verwerking van persoonsgegevens",
    "Artikel 6": "Rechtmatigheid van de verwerking",
    "Artikel 7": "Voorwaarden voor toestemming",
    "Artikel 8": "Voorwaarden voor de toestemming van kinderen met betrekking tot diensten van de informatiemaatschappij",
    "Artikel 9": "Verwerking van bijzondere categorieën van persoonsgegevens",
    "Artikel 10": "Verwerking van persoonsgegevens betreffende strafrechtelijke veroordelingen en strafbare feiten",
    "Artikel 11": "Verwerking waarvoor identificatie niet is vereist",
    "Artikel 12": "Transparante informatie, communicatie en nadere regels voor de uitoefening van de rechten van de betrokkene",
    "Artikel 13": "Informatie die moet worden verstrekt wanneer persoonsgegevens bij de betrokkene worden verzameld",
    "Artikel 14": "Informatie die moet worden verstrekt wanneer de persoonsgegevens niet van de betrokkene zijn verkregen",
    "Artikel 15": "Recht van inzage van de betrokkene",
    "Artikel 16": "Recht op rectificatie",
    "Artikel 17": "Recht op gegevenswissing (‘recht op vergetelheid’)",
    "Artikel 18": "Recht op beperking van de verwerking",
    "Artikel 19": "Kennisgevingsplicht inzake rectificatie of wissing van persoonsgegevens of verwerkingsbeperking",
    "Artikel 20": "Recht op overdraagbaarheid van gegevens",
    "Artikel 21": "Recht van bezwaar",
    "Artikel 22": "Geautomatiseerde individuele besluitvorming, waaronder profilering",
    "Artikel 23": "Beperkingen",
    "Artikel 24": "Verantwoordelijkheid van de verwerkingsverantwoordelijke",
    "Artikel 25": "Gegevensbescherming door ontwerp en door standaardinstellingen",
    "Artikel 26": "Gezamenlijke verwerkingsverantwoordelijken",
    "Artikel 27": "Vertegenwoordigers van niet in de Unie gevestigde verwerkingsverantwoordelijken of verwerkers",
    "Artikel 28": "Verwerker",
    "Artikel 29": "Verwerking onder gezag van de verwerkingsverantwoordelijke of de verwerker",
    "Artikel 30": "Register van de verwerkingsactiviteiten",
    "Artikel 31": "Medewerking met de toezichthoudende autoriteit",
    "Artikel 32": "Beveiliging van de verwerking",
    "Artikel 33": "Melding van een inbreuk in verband met persoonsgegevens aan de toezichthoudende autoriteit",
    "Artikel 34": "Mededeling van een inbreuk in verband met persoonsgegevens aan de betrokkene",
    "Artikel 35": "Gegevensbeschermingseffectbeoordeling",
    "Artikel 36": "Voorafgaande raadpleging",
    "Artikel 37": "Aanwijzing van de functionaris voor gegevensbescherming",
    "Artikel 38": "Positie van de functionaris voor gegevensbescherming",
    "Artikel 39": "Taken van de functionaris voor gegevensbescherming",
    "Artikel 40": "Gedragscodes",
    "Artikel 41": "Toezicht op goedgekeurde gedragscodes",
    "Artikel 42": "Certificering",
    "Artikel 43": "Certificeringsorganen",
    "Artikel 44": "Algemeen beginsel inzake doorgiften",
    "Artikel 45": "Doorgiften op basis van adequaatheidsbesluiten",
    "Artikel 46": "Doorgiften op basis van passende waarborgen",
    "Artikel 47": "Bindende bedrijfsvoorschriften",
    "Artikel 48": "Niet bij Unierecht toegestane doorgiften of verstrekkingen",
    "Artikel 49": "Afwijkingen voor specifieke situaties",
    "Artikel 50": "Internationale samenwerking voor de bescherming van persoonsgegevens",
    "Artikel 51": "Toezichthoudende autoriteit",
    "Artikel 52": "Onafhankelijkheid",
    "Artikel 53": "Algemene voorwaarden voor de leden van de toezichthoudende autoriteit",
    "Artikel 54": "Regels inzake de oprichting van de toezichthoudende autoriteit",
    "Artikel 55": "Competentie",
    "Artikel 56": "Competentie van de leidende toezichthoudende autoriteit",
    "Artikel 57": "Taken",
    "Artikel 58": "Bevoegdheden",
    "Artikel 59": "Activiteitenverslagen",
    "Artikel 60": "Samenwerking tussen de leidende toezichthoudende autoriteit en de andere betrokken toezichthoudende autoriteiten",
    "Artikel 61": "Wederzijdse bijstand",
    "Artikel 62": "Gezamenlijke werkzaamheden van toezichthoudende autoriteiten",
    "Artikel 63": "Coherentiemechanisme",
    "Artikel 64": "Advies van het Comité",
    "Artikel 65": "Geschillenbeslechting door het Comité",
    "Artikel 66": "Spoedprocedure",
    "Artikel 67": "Uitwisseling van informatie",
    "Artikel 68": "Europees Comité voor gegevensbescherming",
    "Artikel 69": "Onafhankelijkheid",
    "Artikel 70": "Taken van het Comité",
    "Artikel 71": "Rapportage",
    "Artikel 72": "Procedure",
    "Artikel 73": "Voorzitter",
    "Artikel 74": "Taken van de voorzitter",
    "Artikel 75": "Secretariaat",
    "Artikel 76": "Vertrouwelijkheid",
    "Artikel 77": "Recht om klacht in te dienen bij een toezichthoudende autoriteit",
    "Artikel 78": "Recht om een doeltreffende voorziening in rechte in te stellen tegen een toezichthoudende autoriteit",
    "Artikel 79": "Recht om een doeltreffende voorziening in rechte in te stellen tegen een verwerkingsverantwoordelijke of een verwerker",
    "Artikel 80": "Vertegenwoordiging van betrokkenen",
    "Artikel 81": "Schorsing van de procedure",
    "Artikel 82": "Recht op schadevergoeding en aansprakelijkheid",
    "Artikel 83": "Algemene voorwaarden voor het opleggen van administratieve geldboeten",
    "Artikel 84": "Sancties",
    "Artikel 85": "Verwerking en vrijheid van meningsuiting en van informatie",
    "Artikel 86": "Verwerking en recht van toegang van het publiek tot officiële documenten",
    "Artikel 87": "Verwerking van het nationaal identificatienummer",
    "Artikel 88": "Verwerking in het kader van de arbeidsverhouding",
    "Artikel 89": "Waarborgen en afwijkingen in verband met verwerking met het oog op archivering, onderzoek en statistiek",
    "Artikel 90": "Geheimhoudingsplicht",
    "Artikel 91": "Gegevensbeschermingsregels van kerken en religieuze verenigingen",
    "Artikel 92": "Uitoefening van de bevoegdheidsdelegatie",
    "Artikel 93": "Comitéprocedure",
    "Artikel 94": "Intrekking van Richtlijn 95/46/EG",
    "Artikel 95": "Verhouding tot Richtlijn 2002/58/EG",
    "Artikel 96": "Verhouding tot eerder gesloten overeenkomsten",
    "Artikel 97": "Commissieverslagen",
    "Artikel 98": "Toetsing van andere Unierechtshandelingen inzake gegevensbescherming",
    "Artikel 99": "Inwerkingtreding en toepassing"
}